apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-play
  labels:
    app: flask-ting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-play
  template:
    metadata:
      labels:
        app: flask-play
    spec:
      containers:
      - name: flask-play
        image: fl-101
        ports:
        - containerPort: 5000
        resources:
          limits: 
            memory: 100Mi
            cpu: 750m
